name: Update ISBN-ranges via generate.py

on:
  workflow_dispatch:
  schedule:
  - cron: '15 4 * * *'

permissions: read-all

jobs:
  run-python-script:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v6

      - name: Run generate.py
        id: generater
        run: cd isbnlib/_data && python generate.py

      - name: Commit changes
        if: steps.generater.outputs.update_required == 'true'
        run: |
          cd isbnlib/_data
          git config --global user.name "[isbn-update-bot]"
          git config --global user.email "actions@github.com"
          git add .
          git diff-index --quiet HEAD || git commit -m "Updated ISBN-range-lists"
          git push
