name: Update ISBN-ranges via generate.py

on:
  workflow_dispatch:

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Run generate.py
        run: cd isbnlib/_data && python generate.py

      - name: Commit changes
        run: |
          cd isbnlib/_data
          git config --global user.name "hans-fritz-pommes"
          git add .
          git diff-index --quiet HEAD || git commit -m "Updated ISBN-range-lists"
          git push
